runtime: nodejs10
# instance_class: B1
# manual_scaling:
#   instances: 1
instance_class: F1
automatic_scaling:
  min_instances: 0
  max_instances: 2
handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
